collegeInfo/urls.py
from django.urls import path
from . import views

app_name = "collegeInfo"

urlpatterns = [
    path("", views.index, name="index"),
    path("departments/", views.department, name="departments"),
    path("gallery/", views.gallery, name="gallery"),
]

rljit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('collegeInfo/', include("collegeInfo.urls")),
    path('', RedirectView.as_view(url="collegeInfo/"))
]

collegeInfo/models.py
from django.db import models

# Create your models here.

class ReachUp(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=60)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=300)
    class Meta:
        db_table = "ReachUp"

    def __str__(self):
        return f"name={self.name} email={self.email} subject={self.subject} message={self.message}"

collegeInfo/views.py
from email.mime.text import MIMEText
from django.shortcuts import render
from django.http import  JsonResponse
import smtplib

from .models import ReachUp
from . import config
# Create your views here.

def index(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        subject = request.POST["subject"]
        message = request.POST['message']
        try:
            ReachUp.objects.create(name=name, email=email, subject=subject, message=message)
            converTime ={
                "name":name,
                "message":"Thank you For your Query kindly we will get back to you"
            }
            #AutomateEmail(email, name)
            return JsonResponse(converTime, status=200)
        except:
            print("error")
    else:
        return render(request, "collegeInfo/index.html")


def department(request):
    return render(request,"collegeInfo/departments.html")

def gallery(request):
    return render(request, "collegeInfo/gallery.html")


#---------------email sending part-------------------------------
def AutomateEmail(email,name):
    msg = MIMEText(f"Dear {name}\n\nThank you for your Query we will get back to you soon\n\n This is an autogenerated mail dont replay it")
    msg['Subject'] = config.subject
    msg['From'] = config.sender_mail
    msg['To'] = email
    server =smtplib.SMTP(config.server_address, config.port)
    server.starttls()
    server.login(config.sender_mail, config.password)
    server.sendmail(config.sender_mail, email, msg.as_string())
    print("Mail Sent")
    server.close()

collegeInfo/templates/collegeInfo/departments.html
{% extends 'base.html' %}
{% block title %}Departments{% endblock title %}


{% block csslinks %}

{% load static %}
<link href="{% static 'css/templatemo-leadership-event.css' %} " rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">


{% endblock csslinks %}


{% block content %}
<section class="venue section-padding" id="computer">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <h2 class="mb-4"><u class="text-info">Computer Science and Engineering</u></h2>
            </div>

            <div class="col-lg-6">
                {% load static %}
                <img src="{% static 'images/homepage/about.jpg' %}" alt="about" width="95%" />
            </div>

            <div class="col-lg-6">
                <p>Department of Computer Science and Engineering was started in the year 2001. The department has well equipped 
                    laboratories with latest configuration and software’s,
                     and has experienced and highly qualified teaching and technical staff members
                </p>
                <p>
                    Department maintains separate library “Jnana Sangama” and the innovative cell for the students and staff for their knowledge
                     thrust and shaping the students innovativeness.
                </p>

            </div>


        </div>
    </div>
</section>



<section class="section-padding" id="ece">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <h2 class="mb-4"><u class="text-info">Electronics and Communications Engineering</u></h2>
            </div>

            <div class="col-lg-6">
                <p>The department of E&CE has highly qualified and excellent professor, Associate professors and Assistant professors. The department is aimed to fill the gap between academic and industry, and also to train the student with sound knowledge to bring awareness of latest technology in the field of electronics and communication engineering. The department is 
                    providing in-depth knowledge for a wide variety of opportunities both in the industry as well as in the R & D fields for the students.
                </p>
                <p>
                    The department faculties and students are involved in organizing of workshops/FDP/National/international conferences and technical paper preparation and presentation for constant upgradation of skills and technical knowledge.The department also motivate the students through forums like IEEE,IETE and ISTE as platform to share the technology updates by the outside resource persons and staff to satisfy industry expectations.The department has separate library, individual counseling rooms, project labs, soft skill department classes, 
                    scientific leasing process and 300 seating capacity seminar hall.
                </p>

            </div>
            <div class="col-lg-6">
                {% load static %}
                <img src="{% static 'images/homepage/ece.jpg' %}" alt="about" width="95%" />
            </div>

        </div>
    </div>
</section>



<section class="venue section-padding" id="computer">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <h2 class="mb-4"><u class="text-info">Mechanical engineering</u></h2>
            </div>

            <div class="col-lg-6">
                {% load static %}
                <img src="{% static 'images/homepage/mech.jpg' %}" alt="about" width="95%" />
            </div>

            <div class="col-lg-6">
                <p>The department was established in the year in 2003 with an intake of 60 students. The department is well equipped with 
                    full – fledged lab facility to meet the academic requirement . It has independent library, seminar hall, internet centre 
                    and computer centre with more than 100 systems to facilitate teaching CAD, CAM, SOLID EDGE, ANSYS and CNC software’s. 
                    Since 2010, the intake was increased to 120 students. The department has highly qualified, experienced, dedicated and 
                    result oriented staff members. The department emphasizes on Research and Development to enlarger extent and the project 
                    works carried out by our students has brought laurels to the department and institution by winning awards at a various levels. 
                    We are proud to say that our department has R & D centre recognized by VTU, Belgaum. The department has a mechanical engineering 
                    forum(AVENTURA), 
                    a platform to share the talents, technology updates by the students, staff and outside resource persons.
                </p>

            </div>


        </div>
    </div>
</section>

{% endblock content %}
{% block jsfiles %}

{% endblock jsfiles %}

collegeInfo/templates/collegeInfo/gallery.html
{% extends 'base.html' %}
{% block title %}Gallery{% endblock title %}


{% block csslinks %}

{% load static %}
<link href="{% static 'css/templatemo-leadership-event.css' %} " rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">


{% endblock csslinks %}


{% block content %}
<section class="venue section-padding" id="section_1">
    <div class="container">
        <div class="row">

            <div class="col-lg-12 col-12">
                <h2 class="mb-4">Our <u class="text-info">Gallery</u></h2>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/cse-dept1.jpg' %}" alt="cse department" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/society.jpg' %}" alt="society" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/ece-dept.jpg' %}" alt="ece department" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/hostel.jpg' %}" alt="hostel" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/canteen.jpg' %}" alt="canteen" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/classroom.jpg' %}" alt="classrooms" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/with-transport.jpg' %}" alt="transport" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/transport1.jpg' %}" alt="transport" width="95%" height="95%"/>
            </div>

            <div class="col-lg-4">
                {% load static %}
                <img src="{% static 'images/gallery/transport2.jpg' %}" alt="transport" width="95%" height="95%"/>
            </div>

        </div>
    </div>
</section>


{% endblock content %}
{% block jsfiles %}

{% endblock jsfiles %}

collegeInfo/templates/collegeInfo/index.html
{% extends 'base.html' %}


        {% block title %}R L Jalappa Institute of Technology{% endblock  %}

        {% block csslinks %}
            <!-- CSS FILES -->
            <style>
                .form-error-msg{
                    color:red;
                    font-size: 12px;
                }
                .custom-form .form-control{
                    margin-bottom:10px !important;
                }
            </style>

            <link rel="preconnect" href="https://fonts.googleapis.com">
            
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

            {% load static %}
            
            <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet">

            <link href="{% static 'css/templatemo-leadership-event.css' %} " rel="stylesheet">

            <link href="{% static 'slick/slick.css' %} " rel="stylesheet">

            <link href="{% static 'slick/slick-theme.css' %} " rel="stylesheet">
        {% endblock  %}
        
        

            {% block content %}
                <section id="section_1">
                    <div class="slick-banner">
                        <div>
                            <a  href="#"><img src="{% static 'images/homepage/placements.jpg' %}" class="image-fluid" height="600" width="100%"/></a>
                        </div>
                        <div>
                            <a  href="#"><img src="{% static 'images/homepage/cse.jpg' %}" class="image-fluid" height="600" width="100%"/></a>
                        </div>
                        <div>
                            <a  href="#"><img src="{% static 'images/homepage/placements.jpg' %}" class="image-fluid" height="600" width="100%"/></a>
                        </div>
                        <div>
                            <a  href="#"><img src="{% static 'images/homepage/cse.jpg' %}" class="image-fluid" height="600" width="100%"/></a>
                        </div>
                    </div>
                </section>


                <section class="venue section-padding" id="section_2">
                    <div class="container">
                        <div class="row">

                            <div class="col-lg-12 col-12">
                                <h2 class="mb-4">Our <u class="text-info">Story</u></h2>
                            </div>

                            <div class="col-lg-6">
                                {% load static %}
                                <img src="{% static 'images/homepage/about.jpg' %}" alt="about" width="95%" />
                            </div>

                            <div class="col-lg-6">
                                <p>R. L. Jalappa Institute of Technology (RLJIT) established in the year 2001 at Doddballapur, 
                                    Bangalore Rural District by Sri R. L. Jalappa, a visionary, social worker and educationist. 
                                    RLJIT is a unit of Sri Devaraj Urs Educational Trust (SDUET) founded in the year 1986 at Kolar to serve the people of rural 
                                    and backward classes. It is approved by AICTE – New Delhi and is affiliated to VTU- Belgaum. The institution is having well qualified, experienced and dedicated team of teaching, 
                                    non-teaching faculty and state of art laboratories in all the departments.
                                </p>
                                <p>
                                    RLJIT is spread across 34 acres of land, amidst greenery gardens having excellent infrastructure with independent block 
                                    for each department, well stacked library, equipped seminar halls, internet, Wi-Fi facility, separate hostels
                                    accommodating 600 students for boys and girls within the campus, 24hrs. medical facility, modern Gymnasium, Indoor games, 
                                    Swimming Pool national standard playgrounds and an open air theater of 2500 seating capacity.
                                </p>

                            </div>


                        </div>
                    </div>
                </section>


                <section class="contact section-padding" id="section_3">
                    <div class="container">
                        <div class="row">

                            <div class="col-lg-12 col-12">
                                <h2 class="mb-4">Our <u class="text-info">Placemets</u></h2>
                            </div>

                            <div class="col-lg-6">
                                {% load static %}
                                <img src="{% static 'images/homepage/placements.jpg' %}" width="95%"  height="95%" alt="" >
                            </div>

                            <div class="col-lg-6">
                                    <p>Our Technical staff and non technical staff are highly supportive for developing the skills set in students and placemets classes make much effective on students.</p>
                                    <p>Achievements on placements</p>
                                    <ul>
                                        <li>we got an best placemets award at Rural Area 2022</li>
                                    </ul>
                            </div>
                        </div>
                    </div>
                </section>

             
                <section class="venue section-padding" id="section_4">
                    <div class="container">
                        <div class="row">

                            <div class="col-lg-12 col-12">
                                <h2 class="mb-5">Here you go <u class="text-info">Venue</u></h2>
                            </div>

                            <div class="col-lg-6 col-12">
                                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3882.799822949041!2d77.5221887148255!3d13.300441490640742!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bb1de5c4a027603%3A0x82a08b0a49f1e9eb!2sR.L.Jalappa%20Institute%20Of%20Technology!5e0!3m2!1sen!2sin!4v1656311092659!5m2!1sen!2sin" width="95%" height="95%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                            
                            <div class="col-lg-6 col-12 mt-5 mt-lg-0">
                                <div class="venue-thumb bg-white shadow-lg">
                                    
                                    <div class="venue-info-title">
                                        <h2 class="text-white mb-0">Times Square</h2>
                                    </div>

                                    <div class="venue-info-body">
                                        <h4 class="d-flex">
                                            <i class="bi-geo-alt me-2"></i> 
                                            <span>Doddaballapur Rd, Kodigehalli</span>
                                        </h4>

                                        <h5 class="mt-4 mb-3">
                                            <a href="mailto:hello@yourgmail.com">
                                                <i class="bi-envelope me-2"></i>
                                                rljitmgmt@rljit.com
                                            </a>
                                        </h5>

                                        <h5 class="mb-0">
                                            <a href="tel: 305-240-9671">
                                                <i class="bi-telephone me-2"></i>
                                                080-124-3222
                                            </a>
                                        </h5>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>

                <section class="contact section-padding" id="section_5">
                    <div class="container">
                        <div class="row">

                            <div class="col-lg-8 col-12 mx-auto">
                                <form class="custom-form contact-form bg-white shadow-lg"  method="post">
                                    <h2 id="formHeading">Please Say Hi</h2>

                                    <div class="row" id="formFields">
                                        <div class="col-lg-4 col-md-4 col-12">                                    
                                            <input type="text" name="txtName" id="txtName" class="form-control" oninput="validateTextbox(this,true,'Enter name')" placeholder="Name" >
                                            <div class="form-error-msg"></div>
                                        </div>

                                        <div class="col-lg-4 col-md-4 col-12">         
                                            <input type="email" name="txtEmail" id="txtEmail" oninput="validateTextbox(this,true,'Enter email')"  class="form-control" placeholder="Email" >
                                            <div class="form-error-msg"></div>
                                        </div>

                                        <div class="col-lg-4 col-md-4 col-12">                                    
                                            <input type="text" name="txtSubject" id="txtSubject" oninput="validateTextbox(this,true,'Enter subject')" class="form-control" placeholder="Subject">
                                            <div class="form-error-msg"></div>
                                        </div>

                                        <div class="col-12">
                                            <textarea class="form-control" rows="5" id="txtMessage" name="txtMessage" oninput="validateTextbox(this,true,'Enter subject')" placeholder="Message"></textarea>
                                            <div class="form-error-msg"></div>
                                        </div>
                                        <button type="button" class="form-control" id="btnSubmit" onclick="submitMsgForm()">Submit</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </section>

            </main>

            
        {% endblock content %}


        {% block jslinks %}
        <!-- JAVASCRIPT FILES -->
{% load static %}
<script src="{% static 'slick/jquery-migrate-1.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'slick/slick.min.js' %}"></script>
{% comment %} <script src="{% static 'js/click-scroll.js' %}"></script> {% endcomment %}
<script src="{% static 'js/custom.js' %}"></script>
<script type="text/javascript">
    var _isFocus;
    $(document).ready(function(){
        $('.slick-banner').slick({
            dots: true,
            infinite: true,
            autoplay:true,
            fade: true,
            cssEase: 'linear'
        });
    });
         
    
    submitMsgForm = function(){
        var save=true
        _isFocus=true
        if(!validateTextbox("#txtName",true,"Enter name")) save=false
        if(!validateTextbox("#txtEmail",true,"Enter email")) save=false
        if(!validateTextbox("#txtSubject",true,"Enter subject")) save=false
        if(!validateTextbox("#txtMessage",true,"Enter message")) save=false

        if(save){
            console.log("form called")
            $("#btnSubmit").attr("disabled",true);
            submitform();
        }
    }

    validateTextbox=function(obj,triggerfocus, message){
        hideError(obj)
        if($(obj).val().trim().length=="0"){
            showError(obj, message)
            if(!_isFocus){
                if(triggerfocus) $(obj).focus()
                _isFocus=true
            }
            return false
        }
        return true                   
    }

    submitform=function(){
        $.ajax({
            type: "POST",
            url: {% url 'collegeInfo:index' %},
            data:{
                "name":$("#txtName").val(),
                "email":$("#txtEmail").val(),
                "subject":$("#txtSubject").val(),
                "message":$("#txtMessage").val(),
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            },
            success: function (xml) {
              onsubmitSuccess(xml);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                console.log(xhr)
            },
          });
    }

    onsubmitSuccess=function(data){
        $("#formHeading").empty().text("Dear "+data.name).append()
        $("#formFields").empty().html("<p>"+data.message+"</p>").append()
    }

    hideError = function(obj){
        $(obj).siblings(".form-error-msg").hide()
    }
                        
    showError = function(obj,msg){
        $(obj).siblings(".form-error-msg").text(msg).show()
    }
</script>
{% endblock jslinks%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
         base
        {% endblock %}
    </title>

    {% load static %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icons/logo.jpg' %}" />

    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">

    <link href="{% static 'css/bootstrap-icons.css' %}" rel="stylesheet">
    {% block csslinks %}
    
    {% endblock csslinks %}
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container">

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a href="{% url 'collegeInfo:index' %}" class="navbar-brand mx-auto mx-lg-0">
                <i class="bi-bullseye brand-logo"></i>
                <span class="brand-text">RLJIT</span>
            </a>


            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:index' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:index' %}#section_2">About</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'collegeInfo:departments' %}">Departments</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:index' %}#section_3">Placements</a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:index' %}#section_4">Venue</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:index' %}#section_5">Contact</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link click-scroll" href="{% url 'collegeInfo:gallery' %}">Gallery</a>
                    </li>

                </ul>
            <div>
                    
        </div>
    </nav>

    {% block content %}
    
    {% endblock content %}


    <footer class="site-footer sticky-wrapper" >
        <div class="container">
            <div class="row align-items-center">

                    <div class="col-lg-12 col-12 border-bottom pb-5 mb-5">
                        <div class="d-flex">
                            <a href="{% url 'collegeInfo:index' %}" class="navbar-brand">
                                <i class="bi-bullseye brand-logo"></i>
                                <span class="brand-text">RLJIT</span>
                            </a>

                            <ul class="social-icon ms-auto">
                                <li><a href="https://www.facebook.com/RLJIT/" class="social-icon-link bi-facebook" target="_blank"></a></li>

                                {% comment %} <li><a href="#" class="social-icon-link bi-instagram"></a></li> {% endcomment %}

                                <li><a href="https://api.whatsapp.com/send?phone=919902516464&app=facebook&entry_point=page_cta" class="social-icon-link bi-whatsapp" target="_blank"></a></li>

                                <li><a href="https://www.youtube.com/channel/UCKi9qmwdDY9q6J1Mmq-lmtQ/videos" class="social-icon-link bi-youtube" target="_blank"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-7 col-12">
                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="{% url 'collegeInfo:index' %}#section_2" class="footer-menu-link">Our Story</a></li>

                            <li class="footer-menu-item"><a href="https://vtu.ac.in/" class="footer-menu-link" target="_blank">University</a></li>

                            <li class="footer-menu-item"><a href="{% url 'collegeInfo:gallery' %}" class="footer-menu-link">Gallery</a></li>

                            <li class="footer-menu-item"><a href="{% url 'collegeInfo:index' %}#section_5" class="footer-menu-link">Contact</a></li>

                            <li class="footer-menu-item"><a href="https://goo.gl/maps/2tBQkvGcZb3TT3KN9" class="footer-menu-link" target="_blank">Map</a></li>
                        </ul>
                    </div>

                            
                    <div class="col-lg-5 col-12 ms-lg-auto">
                        <div class="copyright-text-wrap d-flex align-items-center">
                            <p class="copyright-text ms-lg-auto me-4 mb-0">Copyright © 2022 Rljit. 
                                
                            <br>All Rights Reserved. 
            
                    

                            <a href="#section_1" class="bi-arrow-up arrow-icon custom-link"></a>
                        </div>
                    </div>

                </div>
        </div>
    </footer>

    {% load static %}
    <script src="{% static 'js/jquery.min.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block jslinks %}
    
    {% endblock jslinks %}
</body>
</html>